---
title: "Soil Texture Processing File"
author: "Bailey Lai"
date: "7/26/2016"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading .csv Data into R
```{r}
reading <- "/home/CAMPUS/mwl04747/github/SOPs/Soil_Texture_Analysis/Data/reading.csv"
sample <- "/home/CAMPUS/mwl04747/github/SOPs/Soil_Texture_Analysis/Data/sample.csv"
reading.df <- read.csv(reading)
sample.df <- read.csv(sample)
```

## Check Data Importing
```{r}
#View(reading.df)
head(reading.df)
head(sample.df)
```

## Preprocess Data
```{r preprocess}
library(mosaic)

```
## Join Data with Key.

First, I created two files that have only a few columns each so we can test the join function.

```{r joinkeyID}
reading.tmp <- select(reading.df, sampleKEY, timeElapsed)
sample.tmp <- select(sample.df, sampleKEY, researcher)

left_join(sample.tmp, reading.tmp, by = "sampleKEY")
```


## Merge function used to combine two tables with common variable(s)
test <- merge(reading, sample)
