---
title: "Standards"
author: "Marc Los Huertos"
date: "9/14/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## From Jade Star

I’ve been reading up on standard reference materials with two purposes in mind. First, we want a couple of certified standards with a wide separation of isotope ratio that we can analyze C-N-S isotopes to characterize our the absolute isotope ratios of our tanks of N2 (Air) CO/CO2 (VPDB and VSMOW), and SO2 (VCDT). Such standards should be from sources like the USGS, NIST, or IAEA and only used occasionally as they are precious and expensive, so sold in small quantities. It’s also good that these be more pure than soils to ensure complete combustion of the material. Examples of standards are woods, hair, hoof, and acid (benzoic and glutamic). For example, see these listed at the USGS. 

https://isotopes.usgs.gov/lab/referencematerials.html 

My sense is that we probably want to obtain USGS40 and 41a (glutamic acid), which have a wide range of C-N isotope ratios. We probably would want to get some wood samples for analysis of standards that would be matrix matched to things that we might want to analyze (woody plants, shrubs, trees). 

For a routine standard that is matrix matched to our samples like soils or sediments, we’d be better off using something something like this from EA Consumables 5 gram quantities of soil and sediment that are $110 each. 

https://eaconsumables.com/catalog/product/view/id/387/ 

If we are using it as a regularly analyzed sample for C and N isotopes, 5 grams each of these standards would give us 5000 to 2500 replicates assuming we are burning masses of 1-2 mg of materials =  $0.022 to $0.044/standard = cheap! EA Consumables has a certified value for the soil standard ( $\delta$ 13CVPDB = –26.27±0.15‰; $\delta$ 15N AIR = ±0.29‰)

If people are comfortable with this approach, I will work with Jonathan to buy some for the lab for general use. We might want to obtain the low carbon soil as well. There are many others from this vendor that might be of interest to folks to buy for their own specialty use.

As a last thought, if we have a good dry soil that has good C-N-S concentrations, we can test it out for reproducibiltiy as a potential in house standard and we can also approach the USGS lab in Reston to have them characterize and certify it as an in house standards. 
