%SOP Template 



\documentclass[12pt]{../SOP4_alpha}

\usepackage[english]{babel}
%\usepackage{blindtext}
%\usepackage{lipsum}

%\usepackage[version=4]{mhchem} 
\usepackage{pdfpages}

\title{Soil Loss on Ignition}
\date{7/12/2015}
\author{Ever Cook}
\approved{Los Huertos}
\ReviseDate{\today}
\SOPno{32 v0.1}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

\section{Scope and Application}

\NP Loss on Ignition (LOI) is used to determine organic matter content (OM\%) in soil samples. This is important for indirectly estimating soil organic carbon (SOC) in agricultural topsoil. 

\NP The applications implement SFU Soil Science Lab method (Robertson 2011) and Salehi et. al (2011).

\section{Summary of Method}

\NP This method will cover how to conduct a LOI procedure in the Pomona College Geology Department Lab. Ignition of the soil samples in a muffled furnace burns off any organic matter, leaving only the mineral content. The weight difference of the samples before and after ignition represents the OM\%. This method uses a temperature of 360^\circ$C for 2 hours.

\tableofcontents

\newpage

%\section{Acknowledgements}

%\section{Definitions}

%\NP Crucible


\section{Biases and Interferences}

\NP The following are parameters that might influence the results of the LOI test and thus, we review methods that would best fit the type of soils from our samples.

\begin{description}
  	\item[Clay content] Soil texture has many influences, two of which being climate and parent material 
		\item [Ignition temperature] If the temperature is not hot enough, there may be OM remaining in the samples after ignition.
		\item [Ignition duration] If the samples are not burned for long enough, there may be OM remaining in the samples after ignition.
\end{description}


\section{Health and Safety}

\NP The muffled furnace burns up to 3000$^\circ$C, posing a significant threat to 4th degree burns if precautions aren't taken.

\subsection*{Safety and Personnnel Protective Equipment}

\NP Care should be taken to prevent burns. Remove crucibles from the furnace with tongs and heat-proof gloves. Wait at least 1 hour for them to cool down before handling with bare hands. In case of contact, run skin under cold water for 15 minutes and follow lab procedures for emergency. 

\section{Personnel \& Training Responsibilities}

\NP Researchers training is required before the procedures in this method can be used.

\NP Researchers using this SOP should be trained for the following SOPs:

\begin{itemize}
  \item SOP01 Laboratory Safety
  \item SOP07 Using Balances
  \item SOP15 Using Drying Ovens
\end{itemize}

\newpage 

\section{Required Materials and Apparati}

\begin{enumerate*}
	\item Porcelain crucibles
	\item Soil samples
	\item Muffled furnace
	\item Drying oven
	\item Tongs
	\item Heat-proof gloves
	\item Jack stand
	\item Metal tin
	\item Scoopula
	\item Combustion residue mapping sheet
\end{enumerate*}

\section{Reagents and Standards}

%\begin{enumerate*}
%	\item 
%\end{enumerate*}

\section{Estimated Time}

\NP This procedure requires several days to complete.

%\begin{table}
%\begin{tabular}{llll}\hline
%Task          & Time          & Elapsed Time  & Time until completion \\ \hline\hline
%Collect Soil  & 1-3 hours     & 1-3 hours     &         \\ \hline
%\end{tabular}
%\end{table}

\section{Sample Collection, Preservation, and Storage}



\section{Procedure}

\subsection{Preperation}

\NP Prepare the soil samples in advance in the EA lab. Samples may be sieved with a 2mm sieve.
  The following steps use a drying oven to remove moisture content from the soil and the crucibles that may affect the true dry weights. You can collect soil \% moisture data while simultaneously prepping for LOI.
  
  \begin{enumerate}
	  \item Weigh and record the weight of a labeled metal tin. Add about 3 scoops fo soil using the scoopula into the tin. Record the soil ID, tin #, tin weight, and soil 'wet' mass.
	  \item Oven-dry tins at 105$^\circ$C for 24 hours.
	  \item Once done, open the oven door for about 15 min to cool down. Take samples out of the oven once cool to touch. Weigh and record weigh
	  \item Oven-dry crucibles in the same manner. %Weigh and record crucible weight on the Combustion residue mapping sheet
	\end{enumerate}
	
\subsection{Ignition}

\NP Once ready for ignition, head to the Geo Lab. If the oven is not on already, we can begin heating the oven while preparing the crucibles. Ask the lab technician for help if needed. The Geology Dept. has multiple muffled furnaces. This SOP instructs how to use the Nabertherm furnace 

\NP We will load the furnace while hot and keep it on continuously and overnight until finished with all samples. Frequent reheating can harm the heating coils.

\NP Use the dial knob to set the furnace to the correct program preset called "LOI" and assure it is set to the correct temperature of 360^\circ$C. Press the start button. The LCD screen will tell you the current temperature inside the furnace.

%image

\NP Then, for each sample...
  \begin{enumerate}
	\item Record the weight of the crucible on a scale capable of precision to 0.0001. It may have an assigned #, if not write one with Sharpie on the side of the crucible.
	\item Add oven-dried sample into the crucible.
	\item Weigh and record this as the pre-ignition weight. 
		\end{enumerate}
		
\NP As you prepare the crucibles, use the Combustion Residue Mapping Sheet to map to lay out where you'll put each crucible in the furnace. 8 crucibles can fit in the furnace.
\NP This is important to prevent mixing up samples. Permanent marker will leave a light stain, but shouldn't be relied on. Use the hole on the plate to help you determine direction.

% image here
 
\NP Arrange the crucibles in order on the furnace plate atop the jack stand. The jack stand should be level with the inside of the furnace for easy loading.

\NP Once the furnace is ready, use the tongs and heat-proof gloves push the furnace plate in like so.

% Put image in

\NP Set a timer for 2 hours.

\NP Find something to do in the meantime like prepping the next batch of crucibles.
  
  
  ---------
  

\subsection{Calculating Soil Sample Mass}

\NP We then calculate the ``Total Sample Represented'' in the hydrometer test as the mass of soil in hydrometer test as the oven dry mass used by the percent passed through 2 mm sieve and multiply by 100.


\begin{equation}
W = oven dry mass * percent passing 2mm sieve * 100
\end{equation}

\begin{equation}
WB = \frac{M_{air}*10000}{Per_{No.10} * (100 + Moisture_H)}
\end{equation}



\begin{equation}
DW_{air} = 50/(1+DW_c)
\end{equation}

\noindent and for sandy soils,

\begin{equation}
DW_{air} = 100/(1+DW_c)
\end{equation}



--------


\subsection*{Determining Proportion of Soil Retained No. 200 Sieve}

\NP Particles retained on the No. 200 sieve are larger are often categorized as sand. As the hydrometer does very little to distinshin between size fractionation of sand -- very fine, fine, medium, course, and very course sand. 

\NP But collecting the particles on the No. 200 sieve, we can use seives to better understand the soil characteristics. We can do this by analyzing the mass of the soils retained on the No. 200 sieve, which has a mesh size of XX 0.125 mm.  

\begin{enumerate}
	\item Poor the contents of the cylinder through a No. 200 sieve;
	\item Using the sink with a sediment trap, wash the soil in the sieve until the water leaving the sieve is clear. 
	\item Select a soil tin, and record the tin \# (Box XX) and tin mass (Box XX). 
	\item Carefully wash the soil from the tin into the soil, without damaging the sieve screen. The screens are quite delicate, so using a squeeze bottle is probably best. Using a brush or metal device will force particles into the screen, which can get stuck, distort and stretch the mesh openings or otherwise damage them. 
	\item Weigh the dry soil with the soil tin and record the results in Box Xx.
\end{enumerate}

\section{Recording the Results}

Record the results in Appendix A, Then enter the data into the data entry form (\href{test}{http\\:test}. Other columns calculations will be produced with the R code from Appendix B.  

Do not put commas in text fields -- if you do the download... it will create extra columns and the data will be misaligned.

\section{Data Analysis and Calculations}

Once the data has been entered in the online form, you can extract the data as a csv file. This csv file can then be called by R to calculate the data automatically, using the following functions. 

\subsection*{Importing Data}

Import and check data integrity

<<label=importdata>>=
#hydrometer = import()
#head(hydrometer)
#str(hydrometer)
@

What should you be looking for?  We want to make sure the data shown are the same as expected. There are several ways to look at the data to determine this. I have shown two ways. 1) Looking at the header (first six observations), then we evaluate the structure of the dataframe.
 
\subsection{Calculating effective diameter, $D_e$}


\subsection{Calculating the Percent Finer, PF}


\subsection{Graphing and Interpreting the Results}

\section{QC/QA Criteria}

\section{References}

\NP D422...

\NP Wilde, S.A., R.B. Corey, J.G. Iyer, and G.K. Voigt.  1979.  Soil and Plant Analysis for Tree Culture.  Oxford and IBH Publishing Co., New Delhi.  Pp. 12-13.

\NP Anderson, J.M., and J.S. Ingram, eds.  1993.  Tropical Soil Biology and Fertility:  A Handbook of Methods. 2nd ed.  CAB International, Wallingford, UK.  P. 93-94.

\section{Appendix A. Data Sheet}

\includepdf[pages=-]{DataSheetv3}


\newpage
\section{Appendix B: R code to calculate parameters for the SOP}

% \input{Appendix B}	

\end{document}