%SOP Template 
% Version 02 Added revision date
% Version 03 Added TOC and acknowledgements
%           New SOP3_alpha.cls


\documentclass[12pt]{../SOP4_alpha}

\usepackage[english]{babel}


\title{IDEXX Quanti-Tray}
\date{3/31/2022}
\author{Marc Los Huetos}
\approved{TBD}
\ReviseDate{\today}
\SOPno{23.01}

\begin{document}


\maketitle

\section{Scope and Application}

\NP This standard operating procedure describes the test method for the collection and analysis of water samples for the enumeration of Escherichia coli (E. coli) and
Total coliform bacteria.

\NP The applications of this SOP are for...

\section{Summary of Method}

\NP This SOP does this...

\tableofcontents

\newpage

\section{Acknowledgements}

\section{Definitions}

\NP Term1: is...

\section{Biases and Interferences}

\NP Biases and interferences can come from...

\section{Health and Safety}

\NP Describe the risk...


\subsection{Safety and Personnnel Protective Equipment}

Water quality can range from high quality and even potoble to very low with assorted pathogens or even toxicty. Thus, it's important to take every precuation possible to protect yourself. 

\section{Personnel \& Training Responsibilities}

\NP Researchers training is required before this the procedures in this method can be used... 

\NP Researchers using this SOP should be trained for the following SOPs:

\begin{itemize}
  \item SOP01 Laboratory Safety
  \item SOP02 Field Safety
\end{itemize}

\section{Required Materials and Apparati}

\NP Item 1 w/catalog number!

\NP Item 2

\section{Reagents and Standards}

\section{Estimated Time}

\NP This procedure requires XX minutes...

\section{Sample Collection, Preservation, and Storage}

\section{Procedure}

\NP Prepare \dots

\NP

\section{Data Analysis and Calculations}

\section{QC/QA Criteria}

\NP The detection limit for this analysis is 1 Most Probable Number (MPN) per 100mL of sample. 

\section{Trouble Shooting}

\section{References}

\NP APHA, AWWA. WEF. (2012) Standard Methods for examination of water and wastewater. 22nd American Public Health Association (Eds.). Washington. 1360 pp. (2014).

\end{document}