\documentclass[12pt]{../SOP4_alpha}
\usepackage[english]{babel}
%\usepackage{blindtext}
%\usepackage{lipsum}

%\documentclass{article}

%\documentclass[12pt]{~/github/SOPs/SOP_Template/SOP}

\title{Soil Temperature Testing Procedure}
\date{8/1/2025}
\author{Aaron Rogers}
\approved{Los Huertos}
\ReviseDate{\today}
\SOPno{X}

\begin{document}

\maketitle
\section{Materials}
\NP One Omega Thermometer per 6-8 soil plots
\NP One 12 inch Omega Temperature Probe per thermometer
\NP One 6 inch Omega Temperature Probe per thermometer
\NP One person to measure temperature per 6-8 plots 
\NP Notebook and penicl or laptop to record temperature data 
\NP Thermometer to measure air temperature



\section{Pre Procedure Information}



\section{Procedure}
