\documentclass[12pt]{../SOP4_alpha}
\usepackage[english]{babel}
%\usepackage{blindtext}
%\usepackage{lipsum}

%\documentclass{article}

%\documentclass[12pt]{~/github/SOPs/SOP_Template/SOP}

\title{Soil Temperature Testing Procedure}
\date{8/1/2025}
\author{Aaron Rogers}
\approved{Los Huertos}
\ReviseDate{\today}
\SOPno{X}

\begin{document}

\maketitle
\section{Materials}
\NP One Omega Thermometer per 6-8 soil plots
\NP One 12 inch Omega Temperature Probe per thermometer
\NP One 6 inch Omega Temperature Probe per thermometer
\NP One person to measure temperature per 6-8 plots 
\NP Notebook and penicl or laptop to record temperature data 
\NP Thermometer to measure air temperature


\Section{Time and duration}
\NP One hour twice a day, once from 6am-7am (lowest soil temperature) and once from 4pm-5pm (highest soil temperature)


\section{Pre Procedure Information}
\NP Test all thermometers for accuracy prior to testing, gather all supplies for field work prior to testing
\NP Start morning testing at 6am sharp, afternoon testing at 4pm sharp, testing should be carried out in an hour or less for most accurate recording of low and high temperature
\NP Make an Excel sheet or a manual note sheet to record plot number, soil temperature, and the time soil temperature is recorded
\NP Use R or another program to randomly shuffle the soil plot numbers to allow for random testing
\NP Assign each person 6-8 randomly selected plots
\NP Mark temperature probes with tape at the 2-inch and 4-inch depth on the 6 inch probe, and the 8-inch depth on the 12-inch probe 
\NP Note: 12-inch probe takes longer for temperature stabilization, so temperature testing for both the 2-inch and the 4-inch probe can be conducted while the 8-inch depth temperature testing is being conducted  



\section{Procedure}
