\documentclass[12pt]{../SOP2}
\usepackage[english]{babel}
\usepackage{blindtext}
\usepackage{lipsum}

%\documentclass{article}

%\documentclass[12pt]{~/github/SOPs/SOP_Template/SOP}

\title{Cyanobacteria DNA Extaction from Filtered Samples}
\date{8/11/2016}
\author{Erin Stanfield}
\approved{Los Huertos}
\ReviseDate{\today}
\SOPno{X}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

\section{Scope and Application}

\NP This method involves several prelimary steps to lyse cyanobacteria cells prior to DNA extraction via a modified Quiagen kit protoco.

\NP This method is modiefied from the UCSC Zehr Lab DNA extraction protocol.

\NP Sonication steps are adapate from the "Ultrasonic Lysis: Cell Disruption \& Extraction" protocol found in the Heilsher Ultrasound Technology webpage.

\section{Health and Safety}

\NP \lipsum[2]


\section{Personnel \& Training Responsibilities}

\NP \lipsum[1]

Students using this SOP should be trained for the following SOPsa:

\begin{itemize}
  \item SOP1
  \item SOP2
\end{itemize}


\section{Required Materials}

\subsection{Equipment}

\NP Ultrasonic desmembrator cat?

\NP Water bath or heat block (size?!)

\NP Shaker Incubator?

\NP Vortex mixer

\NP Micropipette (size??)

\section{Supplies}

\NP Qiagen DNeasy kit (Cat \#)

\NP Ice

\NP RNase Away



\section{Estimated Time}

\NP This will take XX minutes...

\section{Procedure}

\NP Prepare \dots

\NP

\section{References}

\NP APHA, AWWA. WEF. (2012) Standard Methods for examination of water and wastewater. 22nd American Public Health Association (Eds.). Washington. 1360 pp. (2014).

\end{document}