\documentclass[12pt]{../SOP4_alpha}
\usepackage[english]{babel}
%\usepackage{blindtext}
%\usepackage{lipsum}

%\documentclass{article}

%\documentclass[12pt]{~/github/SOPs/SOP_Template/SOP}

\title{Nitrate and Ammonium}
\date{6/16/2025}
\author{Aaron Rogers}
\approved{Los Huertos}
\ReviseDate{\today}
\SOPno{X}

\begin{document}

\maketitle

\section{Scope and Application}



\section{Health and Safety}



\section{Personnel \& Training Responsibilities}


Students using this SOP should be trained for the following SOPsa:

\begin{itemize}
  \item SOP1
  \item SOP2
\end{itemize}


\section{Required Materials}

\NP Reciprocating shaker

\NP Graduated cylinder or volumetric flask repipet type dispenser

\NP Filter funnels 

\NP Whatman #42 filter paper

\NP Paper bags or aluminum weigh boats 

\NP Specimen containers or Nalgene bottles 

\NP Test tubes

\NP Pipet

\NP Top-loading balance 


\section{Creating KCL solution}


\NP Weigh out 298.2 g KCL into a 2L volumetric flask 

\NP Fill volumetric flask with distilled water until approximately 2/3rds full

\NP Place volumetric flask on magnetic stirrer and place a magnetic stir bar into the volumetric flask 

\NP Turn magnetic stirrer onto a low to medium level, and leave on for 4 hours

\NP Use stir bar retriver to remove magnetic stir bar 

\NP Fill the volumetric flask up to the 2L mark with distilled water 


\Section{Lab Procedure - Moisture}


\NP Set aside 10g of soil from each soil sample to test for moisture content 

\NP Place each 10g of soil into a weigh boat, dry for 24 hours at 105C, and collect new weight after soil has dried


\Section{Lab Procedure - KCL Extract}


\NP Fill test tubes with 40 ml of KCL solution

\NP Add 7g of soil into container until solution reaches 50 ml

\NP Cap and place on reciprocating shaker for for 2 hours

\NP Allow sample to sit and soil particles to settle (around 10 mins, no more than 1hr)

\NP Place filter paper inside funnels, and set up funnels to drain into labeled specimen containers or new test tubes

\NP Pour shaken solution into into funnels, don't fill funnels above filter paper line 

\NP Allow solution to drain into new container until only soil (no liquid) remains in original container

\NP Filtered solution is now ready to be analyzed. Cap containers and store in a cold location. If analysis will not be completed in the next few days, store the samples in the freezer until analysis.

\begin{table}
\caption{Soil Texture Correction Factor}
\centering
\begin{tabular}{lcc}
Texture     & Moist Soil  & Dry Soil  \\
Sand        &   2.3         &  2.6      \\
Loam        &   2.0       &  2.5      \\
Clay        &   1.7       & 2.2 \\
\end{tabular}
\end{table}


\section{References}

\NP APHA, AWWA. WEF. (2012) Standard Methods for examination of water and wastewater. 22nd American Public Health Association (Eds.). Washington. 1360 pp. (2014).

\end{document}