%SOP Template 
% Version 02 Added revision date
% Version 03 Added TOC and acknowledgements
%           New SOP3_alpha.cls

\documentclass[12pt]{../SOP4_alpha}

\usepackage[english]{babel}

\title{Using Balances}
\date{8/10/2016}
\author{Marc Los Huertos}
\approved{TBD}
\ReviseDate{5/10/23}
\SOPno{07A v.02}

\begin{document}

\maketitle 
Using Everyday Lab Equipment -- Balances

\section{Scope and Application}

\NP The scope of this SOP is  to train researchers to learn and follow the basic protocol of using, cleaning, and operating everyday lab equipment, which includes, the micropipette, glassware equipment, measuring balances, the Vortex, and other marginal lab tools that will be further specified. 

\NP The applications of this SOP are for any basic lab setting for students conducting experiments and/or learning new lab procedures.

\section{Summary of Method}

\NP 

\tableofcontents

\newpage

\section{Acknowledgements}

\section{Definitions}

\NP Term1:


\section{Health and Safety}

\NP Describe the risk...


\subsection*{Safety and Personnnel Protective Equipment}


\section{Personnel \& Training Responsibilities}

\NP Researchers training is required before this the procedures in this method can be used... 

\NP Researchers using this SOP should be trained for the following SOPs:

\begin{itemize}
  \item SOP01 Laboratory Safety
\end{itemize} 

\section{Apparati}

\NP Balances 

\section{Switching on the balance}

\NP When connected to the power supply, the balance automatically switches on.

\NP Before the balance gives reliable results, it must:
\begin{itemize}
\item acclimatize to the room temperature
\item warm up by being connected to the power supply
\end{itemize}
The acclimatization time and warm-up time for balances and comparators are available in "General data".

\NP When the balance is exiting standby, it is ready immediately.


4.5.5 Entering / Exiting standby mode
1 To enter standby mode, hold .
The display is dark. The balance is still switched on.
2 To exit standby mode, press .
The display is turned on.
4.5.6 Switching off the balance
To completely switch off the balance, it must be disconnected from the power supply. By holding , the
balance goes only into standby mode.
Note
When the balance was completely switched off for some time, it must warm up before it can be used.
See also
Switching on the balance   Page 19
4.6 Performing a simple weighing
4.6.1 Zeroing the balance
1 Open the draft shield, if applicable.
2 Clear the weighing pan.
3 Close the draft shield, if applicable.
4 Press to zero the balance.
The balance is zeroed.
4.6.2 Taring the balance
If a sample vessel is used, the balance must be tared.
1 Open the draft shield, if applicable.
2 Clear the weighing pan.
3 Close the draft shield, if applicable.
4 Press to zero the balance.
5 Open the draft shield, if applicable.
6 Place the sample vessel on the weighing pan.
7 Close the draft shield, if applicable.
8 Press to tare the balance.
The balance is tared. The icon
Net
 appears.
4.6.3 Performing a weighing
1 Open the draft shield, if applicable.
2 Place the weighing object into the sample vessel.
3 Tap Add result if you want to report the weighing result.
The result is added to the Results list.
4.6.4 Completing the weighing
1 To save the Results list, tap Complete.
The window Complete task opens.
2 Select an option to save or print the Results list.
The respective dialog opens.
3 Follow the instructions from the wizard.
4 Tap Complete.
The Results list is saved/printed and then cleared



\section{QC/QA Criteria}

\subsection{Leveling the balance}

\NP Exact horizontal and stable positioning are essential for repeatable and accurate weighing results.

If the message Balance is out of level appears:

\NP Tap Level the balance. The Leveling aid opens.
 
\NP Follow the instructions from the wizard.

\NP The leveling aid can also be accessed through the Balance menu:

Navigation: Balance menu > Leveling aid

\subsection{Performing an internal adjustment}

Navigation: Methods > Adjustments
The adjustment Strategy is set to Internal adjustment.
1 Open the Methods section, tap Adjustments, select the adjustment, and tap Start
- or -
from the main weighing screen, tap More and tap Start adjustment.
Internal adjustment is being executed.
When the adjustment has been completed, an overview of the adjustment results appears.
2 Tap Print if you want to print the results.
3 Tap Finish adjustment.
The balance is ready.
Precision Balances and Comparators 19

\section{References}

\NP APHA, AWWA. WEF. (2012) Standard Methods for examination of water and wastewater. 22nd American Public Health Association (Eds.). Washington. 1360 pp. (2014).

\end{document}