\documentclass[12pt]{SOP5_beta}
\usepackage[english]{babel}
\usepackage{blindtext}
\usepackage{lipsum}

%\documentclass{article}

%\documentclass[12pt]{~/github/SOPs/SOP_Template/SOP}

\title{Soil Moisture}
\date{6/16/2025}
\author{Marc Los Huertos}
\approved{Los Huertos}
\ReviseDate{\today}
\SOPno{20-16 v0.1}

\begin{document}

\maketitle

\section{Scope and Application}

\NP 

\section{Health and Safety}

\NP \lipsum[2]


\section{Personnel \& Training Responsibilities}

\NP \lipsum[1]

Students using this SOP should be trained for the following SOPsa:

\begin{itemize}
  \item SOP1
  \item SOP2
\end{itemize}


\section{Required Materials}

\subsection{Reagents}

\NP None 


\subsection{Equipment}

\NP Drying Oven

\section{Estimated Time}

\NP This will take XX minutes...

\section{Procedure}

\NP 


subsection{Calculations}

\NP 


\section{References}

\NP APHA, AWWA. WEF. (2012) Standard Methods for examination of water and wastewater. 22nd American Public Health Association (Eds.). Washington. 1360 pp. (2014).

\end{document}