{
  "hash": "abf4ed34834a5cd8dab1e1cd474e5d9e",
  "result": {
    "engine": "knitr",
    "markdown": "---\n# =============================================================================\n# SOP-L700: DNA Extraction, Quantification, and Purity Assessment\n# =============================================================================\ntitle: \"DNA Extraction, Quantification, and Purity Assessment\"\nsop-number: \"SOP-L700\"\nauthor:\n  - name: \"Marc Los Huertos\"\n    affiliation: \"EA Program, Pomona College\"\ndate: last-modified\ndate-format: \"YYYY-MM-DD\"\nrevision: \"1.0\"\n\nrevision-history:\n  - version: \"1.0\"\n    date: \"2025-05-14\"\n    author: \"Marc Los Huertos\"\n    changes: \"Initial release\"\n---\n\n## Purpose\n\nThis procedure describes the extraction of genomic DNA from environmental\nsamples (soil, sediment, water filters, and plant tissue), followed by\nquantification of DNA concentration and assessment of DNA purity using\nspectrophotometric and fluorometric methods. The protocol is based on\ncommercial bead-beating extraction kits and is suitable for downstream\napplications including PCR amplification, qPCR, and amplicon sequencing\n[@dneasy2024; @qiagen_powersoil2024].\n\n\n## Scope\n\n- **Applies to:** Genomic DNA extraction from soil, sediment, water filter\n  membranes, and plant tissue using the DNeasy PowerSoil Pro Kit (Qiagen)\n  or equivalent bead-beating kit; DNA quantification using a NanoDrop\n  spectrophotometer and Qubit fluorometer\n- **Does not apply to:** RNA extraction, plasmid isolation, ancient DNA,\n  or clinical/diagnostic samples\n- **Location:** Molecular biology bench, Pomona College Biogeochemistry Lab\n\n\n## Responsibilities\n\n| Role              | Responsibility                              |\n|:------------------|:--------------------------------------------|\n| Lab PI            | Approve SOP, ensure training compliance     |\n| Trained Personnel | Follow this SOP, report deviations          |\n| New Students      | Complete training before independent use    |\n\n<!-- Definitions snippet for SOP-L700: DNA Extraction -->\n<!-- Insert immediately before ## Safety and Hazards -->\n\n## Definitions\n\n- **A~260~/A~280~ ratio:** The ratio of absorbance at 260 nm to 280 nm; pure dsDNA yields ~1.8; values below 1.7 indicate protein or phenol contamination that may inhibit PCR amplification.\n- **A~260~/A~230~ ratio:** The ratio of absorbance at 260 nm to 230 nm; values of 2.0--2.2 indicate pure nucleic acids; low values indicate contamination with chaotropic salts, humic acids, or carbohydrates.\n- **Bead beating:** Mechanical cell lysis in which sample is agitated at high speed with ceramic or glass beads in a tube; disrupts cell walls and membranes including the tough walls of fungal spores and gram-positive bacteria.\n- **Chaotropic salt:** A salt (e.g., guanidinium isothiocyanate, guanidinium hydrochloride) that disrupts hydrogen bonds and hydrophobic interactions; used in DNA extraction to denature proteins and facilitate binding of DNA to silica membranes.\n- **Environmental DNA (eDNA):** Genetic material shed into the environment by organisms through mucus, feces, skin cells, and gametes; collected from soil, water, or air without organism capture.\n- **Inhibitor:** A substance co-extracted with DNA that reduces PCR amplification efficiency; common inhibitors in soil and water eDNA include humic acids, tannins, heavy metals, and residual ethanol.\n- **Silica column (spin column):** A miniaturized chromatography column containing a silica membrane that selectively binds DNA in the presence of chaotropic salts; DNA is washed and then eluted with low-salt buffer or water.\n\n\n## Safety and Hazards\n\n::: {.callout-warning}\n### Hazards\n\n- **Chemical:** Lysis buffer contains guanidine salts, which are harmful\n  if swallowed or inhaled and can cause skin and eye irritation. Solution\n  C4 contains ethanol. Review the Safety Data Sheets (SDS) for all kit\n  reagents before use.\n- **Physical:** Bead-beating generates aerosols; keep tubes sealed during\n  vortexing. Centrifuge rotor imbalance can cause equipment damage.\n- **Biological:** Environmental samples may contain unknown pathogens.\n  Treat all samples as potentially infectious [@cdc_bmbl2020].\n:::\n\n### Required PPE\n\n- [ ] Safety glasses or goggles\n- [ ] Lab coat\n- [ ] Nitrile gloves (change frequently to avoid cross-contamination)\n- [ ] Face shield (if working with large volumes of lysis buffer)\n\n### Emergency Procedures\n\nIn case of chemical splash or skin/eye contact, flush affected area with\nwater for at least 15 minutes and consult the SDS. For spills of lysis\nbuffer, absorb with paper towels, clean with water, and dispose as\nchemical waste. Refer to\n[SOP-L003 Hazardous Materials Handling](SOP-L003-hazardous-materials-handling.qmd)\nfor general chemical spill response.\n\n\n## Equipment and Materials\n\n### Equipment\n\n| Item                            | Location         | Notes                          |\n|:--------------------------------|:-----------------|:-------------------------------|\n| Vortex adapter for bead tubes   | Mol bio bench    | Holds 24 tubes horizontally    |\n| Vortex-Genie 2                  | Mol bio bench    | Set to maximum speed           |\n| Microcentrifuge                 | Mol bio bench    | Must reach 10,000 x g minimum  |\n| NanoDrop One spectrophotometer  | Instrument bench | UV-Vis micro-volume            |\n| Qubit 4 fluorometer             | Instrument bench | For dsDNA quantification       |\n| Micropipettes (10, 100, 1000 uL)| Mol bio bench   | Calibrated annually            |\n| --80 C freezer                  | Cold room        | For long-term DNA storage      |\n| --20 C freezer                  | Lab              | For short-term DNA storage     |\n\n### Reagents and Consumables\n\n| Item                                  | Catalog No.       | Storage          |\n|:--------------------------------------|:------------------|:-----------------|\n| DNeasy PowerSoil Pro Kit (Qiagen)     | 47014 (50 prep)   | Room temperature |\n| Qubit dsDNA BR Assay Kit              | Q32850            | Room temperature |\n| Qubit dsDNA HS Assay Kit              | Q32851            | Room temperature |\n| Qubit assay tubes (0.5 mL)            | Q32856            | Room temperature |\n| Nuclease-free water                   | Various           | Room temperature |\n| Molecular-grade ethanol (100%)        | Various           | Flammables cabinet |\n| 1.5 mL microcentrifuge tubes (DNase-free) | Various       | Room temperature |\n| Filter pipette tips (10, 100, 1000 uL)| Various          | Room temperature |\n\n\n## Procedure\n\n### Sample Preparation\n\n1. Record sample identity, collection date, and mass/volume in the lab\n   notebook and in the\n   [Freezer Inventory Google Sheet](<!-- LINK_PLACEHOLDER: replace with Google Sheet URL -->)\n2. For soil/sediment: weigh 0.20--0.25 g of sample into the PowerBead Pro\n   tube. Record exact mass.\n3. For water filters: use sterile forceps to transfer the membrane filter\n   into the PowerBead Pro tube. Cut the filter into strips if needed to\n   fit inside the tube.\n4. For plant tissue: weigh 0.02--0.10 g of tissue (fresh or flash-frozen)\n   into the PowerBead Pro tube. Use less tissue for highly mucilaginous\n   samples [@doyle1987].\n\n::: {.callout-important}\nKeep samples on ice during preparation to minimize DNA degradation by\nendogenous nucleases. Process all samples within a single batch if\npossible to reduce extraction variability [@frostegard1999].\n:::\n\n### Cell Lysis and DNA Extraction\n\nFollow the DNeasy PowerSoil Pro Kit protocol [@qiagen_powersoil2024]:\n\n1. Add 800 uL of Solution CD1 to the PowerBead Pro tube\n2. Secure tubes horizontally on the vortex adapter and vortex at maximum\n   speed for 10 minutes\n3. Centrifuge at 15,000 x g for 1 minute\n4. Transfer the supernatant to a clean 2 mL collection tube\n5. Add 200 uL of Solution CD2, vortex briefly (5 seconds), and centrifuge\n   at 15,000 x g for 1 minute\n6. Avoiding the pellet, transfer the supernatant to a clean 2 mL\n   collection tube\n7. Add 600 uL of Solution CD3, vortex briefly (5 seconds)\n8. Load 650 uL onto an MB Spin Column seated in a 2 mL collection tube.\n   Centrifuge at 15,000 x g for 1 minute. Discard flow-through. Repeat\n   to load remaining lysate.\n9. Add 500 uL of Solution EA. Centrifuge at 15,000 x g for 1 minute.\n   Discard flow-through.\n10. Add 500 uL of Solution C5 (wash buffer). Centrifuge at 15,000 x g for\n    1 minute. Discard flow-through.\n11. Centrifuge again at 16,000 x g for 2 minutes to remove residual wash\n    buffer\n12. Transfer the MB Spin Column to a clean 1.5 mL microcentrifuge tube\n13. Add 50--100 uL of Solution C6 (elution buffer) or nuclease-free water\n    to the center of the membrane. Allow to stand for 1 minute at room\n    temperature, then centrifuge at 15,000 x g for 1 minute.\n\n::: {.callout-tip}\n### Tip\nUse a smaller elution volume (50 uL) when higher DNA concentration is\nneeded for downstream applications. A second elution with an additional\n50 uL can recover 10--20% more DNA but at lower concentration\n[@qiagen_powersoil2024].\n:::\n\n### DNA Quantification -- NanoDrop Spectrophotometry\n\nThe NanoDrop measures DNA concentration and provides absorbance ratios\nused to assess purity [@desjardins2010]:\n\n1. Clean the pedestal with 2 uL of nuclease-free water; wipe with a\n   lint-free tissue\n2. Blank the instrument with 2 uL of the elution buffer (Solution C6 or\n   nuclease-free water, matching your elution)\n3. Load 2 uL of DNA extract onto the pedestal\n4. Record the concentration (ng/uL), A~260~/A~280~ ratio, and\n   A~260~/A~230~ ratio for each sample\n\n### DNA Quantification -- Qubit Fluorometry\n\nThe Qubit fluorometer uses fluorescent dyes that bind selectively to\ndsDNA, providing more accurate quantification than spectrophotometry,\nespecially at low concentrations or in the presence of contaminants\n[@invitrogen_qubit2024]:\n\n1. Prepare the Qubit working solution: dilute the Qubit dsDNA BR (or HS)\n   reagent 1:200 in Qubit buffer. Prepare enough for all samples plus two\n   standards (e.g., 200 uL per assay tube).\n2. Prepare standards: add 190 uL of working solution to each of two Qubit\n   assay tubes. Add 10 uL of Standard 1 to one tube and 10 uL of\n   Standard 2 to the other. Vortex briefly.\n3. Prepare samples: add 198 uL of working solution to a Qubit assay tube.\n   Add 2 uL of DNA extract. Vortex briefly.\n4. Incubate all tubes at room temperature for 2 minutes (but not longer\n   than 30 minutes)\n5. Calibrate the Qubit with the two standards, then read each sample\n6. Record the concentration (ng/uL, corrected for dilution by the\n   instrument)\n\n### DNA Purity Assessment\n\nEvaluate DNA purity using the NanoDrop absorbance ratios\n[@wilfinger1997; @desjardins2010]:\n\n| Ratio           | Ideal Range   | Interpretation                              |\n|:----------------|:--------------|:--------------------------------------------|\n| A~260~/A~280~   | 1.8--2.0      | Values below 1.8 suggest protein or phenol contamination |\n| A~260~/A~230~   | 2.0--2.2      | Values below 2.0 suggest contamination with humic acids, carbohydrates, salts, or residual guanidine from extraction buffers |\n\n::: {.callout-note}\nFor environmental DNA extracts, especially from humic-rich soils,\nA~260~/A~230~ ratios are frequently below 2.0. If downstream applications\n(e.g., PCR) fail or show inhibition, consider additional cleanup using a\nOneStep PCR Inhibitor Removal Kit or gel purification [@young2014].\n:::\n\n### Storage and Freezer Inventory\n\n1. Label each tube with: sample ID, extraction date, elution volume, and\n   concentration (in ng/uL)\n2. For short-term storage (less than 1 month): store DNA extracts at\n   --20 C\n3. For long-term storage: store DNA extracts at --80 C in the designated\n   molecular biology section of the freezer\n4. Record the storage location (freezer, rack, box, and position) in the\n   [Freezer Inventory Google Sheet](<!-- LINK_PLACEHOLDER: replace with Google Sheet URL -->)\n5. Update the Google Sheet immediately upon placing samples in the freezer\n   or removing them\n\n::: {.callout-important}\n### --80 C Freezer Protocol\n\n- Minimize the time the freezer door is open. Retrieve the correct box\n  before opening the freezer.\n- Place DNA extracts in designated cryoboxes labeled \"DNA Extracts\" with\n  the project name and date range.\n- Do not store DNA extracts in the same box as tissue samples or reagents.\n- Avoid repeated freeze-thaw cycles. If multiple downstream analyses are\n  planned, prepare aliquots at the time of extraction [@shao2012].\n:::\n\n\n## Quality Control and Acceptance Criteria\n\n- Include one extraction blank (empty PowerBead Pro tube processed through\n  the full protocol) per extraction batch to detect contamination\n  [@salter2014]\n- Run Qubit standards with each new batch of working solution\n- Acceptable DNA yield from 0.25 g of soil: typically 1--20 ng/uL in a\n  100 uL elution, depending on soil type [@dineen2010]\n- Acceptable A~260~/A~280~: 1.7--2.0. Samples outside this range should\n  be noted and may require re-extraction.\n- Acceptable A~260~/A~230~: greater than 1.5 for most downstream\n  applications. Values below 1.0 indicate significant contamination and\n  the extract should be purified or re-extracted.\n- If NanoDrop and Qubit concentrations disagree by more than a factor of\n  two, the NanoDrop reading is likely inflated by contaminants; use the\n  Qubit value for planning downstream reactions [@nakayama2016].\n\n\n## Waste Disposal\n\n| Waste Type                    | Container                 | Disposal Method                     |\n|:------------------------------|:--------------------------|:------------------------------------|\n| Used PowerBead Pro tubes      | Biohazard bag             | Autoclave, then standard trash      |\n| Flow-through from spin columns| Chemical waste carboy      | EH&S hazardous waste pickup (contains guanidine salts) |\n| Used spin columns             | Chemical waste bag         | EH&S hazardous waste pickup         |\n| Pipette tips and tubes        | Biohazard sharps/trash     | Standard biohazard disposal         |\n| Empty reagent bottles         | Rinse and recycle          | Check SDS for specific instructions |\n\n\n## References\n\n::: {#refs}\n:::\n\n\n## Training Record\n\nBefore performing this procedure independently, personnel must:\n\n1. Read this SOP and [SOP-L003 Hazardous Materials Handling](SOP-L003-hazardous-materials-handling.qmd) in full\n2. Review the SDS for all kit components (especially Solutions CD1, CD2,\n   and CD3)\n3. Complete the Qiagen DNeasy PowerSoil Pro Kit quick-start guide\n4. Demonstrate competence with micropipetting, the NanoDrop, and the\n   Qubit fluorometer\n5. Perform a full extraction under supervision, including quantification\n   and freezer logging\n6. Be signed off by the PI or lab manager\n\n\n## Appendix A: Troubleshooting {.appendix}\n\n| Symptom                          | Probable Cause                     | Corrective Action                          |\n|:---------------------------------|:-----------------------------------|:-------------------------------------------|\n| Very low DNA yield               | Insufficient lysis; too little starting material | Increase vortexing time to 15 min; verify sample mass |\n| Low A~260~/A~280~ (below 1.6)    | Protein carryover                  | Re-extract with fresh kit reagents; ensure full removal of CD2 pellet |\n| Low A~260~/A~230~ (below 1.0)    | Humic acid or guanidine carryover  | Add a second C5 wash step; use inhibitor removal kit |\n| NanoDrop reads much higher than Qubit | Co-extracted contaminants inflating UV absorbance | Trust Qubit value; consider cleanup before downstream use |\n| PCR inhibition despite good yield | Co-extracted humic acids or polysaccharides | Dilute template 1:10; use inhibitor-tolerant polymerase; clean up with OneStep kit [@young2014] |\n| Extraction blank shows amplification | Reagent or cross-contamination  | Discard batch; use fresh reagents; clean workspace with 10% bleach then ethanol |\n\n\n## Appendix B: DNA Concentration Calculation Worksheet {.appendix}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate total DNA yield from extraction\nelution_vol_uL <- 100        # Volume of elution buffer used (uL)\nqubit_conc_ng_uL <- 8.5      # Qubit reading (ng/uL)\nsample_mass_g <- 0.25         # Starting sample mass (g)\n\ntotal_dna_ng <- qubit_conc_ng_uL * elution_vol_uL\ndna_per_g <- total_dna_ng / sample_mass_g\n\ncat(sprintf(\"Total DNA yield: %.1f ng\\n\", total_dna_ng))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal DNA yield: 850.0 ng\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"DNA yield per gram of sample: %.1f ng/g\\n\", dna_per_g))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDNA yield per gram of sample: 3400.0 ng/g\n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}