---
title: "Guide Guide for Trouble Shooting Picarro"
author: "Marc Los Huertos"
date: "10/31/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Communication with Pomona College

The best and easiest way...

Marc Los Huertos, 909-451-3373

Unfortunately, until I have my rack mount monitor back, we have to use the key board and and external screen (in the box next to the instrument box) to see what the computer is doing. Ugh!  So, Marc can walk you through that. 

Get a short or towel and some duct tape. Attach the towel to the LCD screen so you can see it in the sun. 

Next start "Teamviewer 14" and when you get the password, tell Marc, since he can control and fix most of the problems from a remote computer this way. The icon is on the top left corner of the LCD screen. 

## Power Failure

If the power fails and then turns back on, it's likely that the computer restarted, but the software to operate the chambers has not come back on-line.

### Computer Restarted and Picarro Software Did Not Restart

### Computer Restarted and Picarro Software Restarted

This is the most common outcome after a power failure. Unfotunately, it takes about 30 min. to get everything back online.




## Chambers Failing to Open and/or Close

The problem can be from a bad cable, software communication problems, or mechanical failure of the chambers. If a chamber if failing to remain open when not sampling, please not the chamber ID and report it back to Marc.

Trouble shooting this is difficult without a detailed understanding of how the Eosense chambers are connected to the multiplexer. Marc will drive to Yuma with spare chambers and cables to determine the source of the problem. 


